### PR TITLE
Bump React version to 18.2.0

### PR DESCRIPTION
**Pull request by quedicesebas**
I need to use this useful library with a new React project. The version restriction cost me a lot of trouble.

I changed the dependencies and the build works after that. Anything else need to be done?

### CODE REVIEW

**Comment by hannadrehman** [comment]
thanks @quedicesebas. appreciate your effort. unfortunately we dont have test cases yet.  i will spend some time on this weekend and manually test everything. if things are fine will merge this pr

**Comment by quedicesebas** [comment]
@hannadrehman i f you want, we can organize ways to contribute to the project.

**Comment by hannadrehman** [comment]
> @hannadrehman i f you want, we can organize ways to contribute to the project.

would love that.

**Comment by hannadrehman** [comment]
@quedicesebas   i tried out with react 18.  not facing any issues with current versions. 
here is a codesandbox for the same. 
https://codesandbox.io/s/friendly-paper-uijcd8?file=/src/_app.js

**Comment by quedicesebas** [comment]
@hannadrehman I had problems with a lot of libraries, I had to install the library using --legacy-peer-deps npm flag *and use it with libraries installed after that) and use that flag in the CI jobs and deploy flow in aws.

**Comment by quedicesebas** [comment]
Closed because of #32

**Comment by hannadrehman** [comment]
@quedicesebas  i am looking for people who can help me with the maintenance of this project. if u are interested lets connect on that :)

**Comment by quedicesebas** [comment]
Contact me :)

**Pull request closed without merging**
